### ISSUE TITLE
lz4 compression algorithm

### ISSUE THREAD

**Issue by privatus** [s3ql/s3ql#107]
lz4 compression algorithm (e.g. used in ZFS) is much faster than lzma and bzip2.
https://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO
It would be very useful if s3ql could use lz4.

**Comment by Nikratio** [comment]
This is a great idea, thanks for taking the time to suggest it! Do you think you could work on this (or do you know someone who could)?

S3QL is a fully volunteer driven project[1]. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

[1] Actually, that's not strictly true. I do offer paid consulting with discounts for code that makes it into the official S3QL release. Contact me privately if that's something you'd be interested in.

**Comment by privatus** [comment]
I am not Python developer, but I will try to do some research.

**Comment by privatus** [comment]
lz4 Python library is on https://pypi.org/project/lz4/. "This package provides python bindings for the LZ4 compression library https://lz4.github.io/lz4/"; "these LZ4 bindings should provide a drop-in alternative to the compression libraries shipped with Python"

**Comment by Nikratio** [comment]
I'm closing this issue for now. This isn't meant to be a rejection of the idea itself, it's just that there is little point in keeping enhancement/wishlist requests in the bug tracker that no-one intends to work on. (I want to use the tracker as a tool to manage ongoing work rather than a database of possible enhancements).

**Comment by ainiml** [comment]
> I'm closing this issue for now. This isn't meant to be a rejection of the idea itself, it's just that there is little point in keeping enhancement/wishlist requests in the bug tracker that no-one intends to work on. (I want to use the tracker as a tool to manage ongoing work rather than a database of possible enhancements).

Is there a list we can add to for feature requests that may be worked on? I haven't had the chance to get into it, but I needed `extent` support for running Longhorn over s3ql.
