### ISSUE TITLE
Support OpenStack v3 auth

### ISSUE THREAD

**Issue by vvdancila** [s3ql/s3ql#108]
For OpenStack Rocky, which is configured to use keystone V3 s3ql is unable to find the containers.

The command returns 404

`2019-06-25 07:24:24.062 30717 ERROR    MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 85, in _container_exists
    self._do_request('GET', '/', query_string={'limit': 1 })
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 229, in _do_request
    self.conn =  self._get_conn()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/backends/swiftks.py", line 98, in _get_conn
    raise HTTPError(resp.status, resp.reason, resp.headers)
s3ql.backends.s3c.HTTPError: 404 NOT FOUND`

**Comment by Nikratio** [comment]
Thanks for the report! S3QL only supports keystone v2, so this is probably the reason for the failure (although the error message does not look directly related).

Do you think you could work on this (or do you know someone who could)?

S3QL is a fully volunteer driven project[1]. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

[1] Actually, that's not strictly true. I do offer paid consulting with discounts for code that makes it into the official S3QL release. Contact me privately if that's something you'd be interested in.

**Comment by vvdancila** [comment]
Hello, 
The source of src/s3ql/swiftks.py was changed to support v3 in the following manner:
`        auth_body = {
                    "auth": {
                        "identity": {
                            "methods": [
                                "password"
                            ],
                            "password": {
                                "user": {
                                    "domain": {
                                        "id": "default"
                                    },
                                    "name": user,
                                    "password": self.password
                                }
                            }
                        },
                        "scope": {
                            "project": {
                                "domain": {
                                    "id": "default"
                                },
                            "name": tenant
                            }
                        }
                    }
                }

        with HTTPConnection(self.hostname, port=self.port, proxy=self.proxy,
                            ssl_context=ssl_context) as conn:
            conn.timeout = int(self.options.get('tcp-timeout', 20))

            conn.send_request('POST', '/v3/auth/tokens', headers=headers,
                              body=json.dumps(auth_body).encode('utf-8'))
            resp = conn.read_response()

            if resp.status == 401:
                raise AuthorizationError(resp.reason)

            elif resp.status > 299 or resp.status < 200:
                raise HTTPError(resp.status, resp.reason, resp.headers)

            cat = json.loads(conn.read().decode('utf-8'))
            self.auth_token = resp.headers['X-Subject-Token']

        avail_regions = []
        for service in cat['token']['catalog']:
            if service['type'] != 'object-store':
                continue

            for endpoint in service['endpoints']:
                if endpoint['region'] != self.region:
                    avail_regions.append(endpoint['region'])
                    continue

                o = urlsplit(endpoint['url'])
                self.auth_prefix = urllib.parse.unquote(o.path)
                if o.scheme == 'https':
                    ssl_context = self.ssl_context
                elif o.scheme == 'http':
                    ssl_context = None
                else:
                    # fall through to scheme used for authentication
                    pass

`

If both v2 and v3 should be supported further changes need to be made in order to switch from v2 to v3 auth type.

Thank you!

**Comment by Nikratio** [comment]
Could you send a pull request?

**Comment by Nikratio** [comment]
(pull request was merged)
