### ISSUE TITLE
Crashes when running out of file descriptors

### ISSUE THREAD

**Issue by dgilman** [s3ql/s3ql#125]
While doing an rsync copy of a filesystem with many small files into an s3ql mount my system ran out of file descriptors. In the dmesg:

    [6628268.444644] VFS: file-max limit 385378 reached

And then, in the s3ql logs:

    Oct 06 12:36:52 mount.s3ql[20836]: handler raised <class 'OSError'> exception ([Errno 23] Too many open files in system: '/home/bkups/.s3ql/gs:redacted-cache/1089469-0'), terminating main loop.
    Oct 06 12:36:52 mount.s3ql[20836]: libgcc_s.so.1 must be installed for pthread_cancel to work
    Oct 06 12:36:52 mount.s3ql[20836]: Fatal Python error: Aborted

Followed by a stack trace of every thread in the s3ql daemon. Not sure what caused the file descriptor limit to be hit, I haven't messed with `--max-cache-entries` on the mount and my ulimit -n for the s3ql user is 1024. No idea what caused all the files to be open, if you think it could have been s3ql I can try any triage you suggest but I wonder if something else was the culprit here.

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

S3QL is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).
