### ISSUE TITLE
Add AWS4-HMAC-SHA256 authorization to S3C backend

### ISSUE THREAD

**Issue by redneb** [s3ql/s3ql#131]
I was trying to create an s3ql filesystem on Oracle cloud's object storage. They provide an API that is compatible with S3 so I attempted to use s3ql's `s3c` backend but I am getting the following error:

    The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

By looking at s3ql's code, it appears that `AWS4-HMAC-SHA256` is implemented for the `s3` backend but not for `s3c`. Is there any chance we can get this in the `s3c` backend as well?

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

S3QL is a volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by redneb** [comment]
Even though I don't know python, I will give it a shot.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
