### ISSUE TITLE
Increasing reliability of writing to disk (Deleted spurious object)

### ISSUE THREAD

**Issue by ainiml** [s3ql/s3ql#144]
In trying to find a balance between `cachesize` and ensuring the dirty cache would be written to disk

It seems even when the dirty cache has been committed, and is down to zero, we still get hundreds of:

```
WARNING: Deleted spurious object 534585
WARNING: Deleted spurious object 534593
WARNING: Deleted spurious object 534594
WARNING: Deleted spurious object 534595
WARNING: Deleted spurious object 534596
```

Currently, uncertain where to check, either in the networking to ensure data has been written, or the dirty cache, to ensure it isn't removed from it before data written is verified.  

Still investigating

Maybe related: https://github.com/s3ql/s3ql/issues/102

**Comment by Nikratio** [comment]
These messages are because there are objects in the backend that should not be there, in other words you have killed the filesystem while it was still busy deleting objects. The queue of objects to be deleted is not stored in the cache, so you can have a clean cache but still a large number of outstanding removals.
