### ISSUE TITLE
s3ql and AWS assume role

### ISSUE THREAD

**Issue by Kirin-kun** [s3ql/s3ql#145]
Hello,

Maybe the answer is already out there, but I didn't find it.

Is there a way to make s3ql commands use an assumed role to access the s3 bucket?

Basically, my s3 buckets can be accessed only with a specific IAM role, so I  either use a profile, or temporary credentials using aws sts.

Example:

`aws sts assume-role --role-arn arn:aws:iam::123456789:role/admin --role-session-name s3access --profile default`

Which gives me back temporary credentials with aws key, aws secret and aws_token.

I tried this with awscli and it works perfectly if I update the .aws/credentials file with  aws_access_key_id, aws_secret_access_key and aws_session_token

All 3 are mandatory, or aws s3 commands don't work.

I originally thought I could just create a authinfo file with these informations so s3ql can access my bucket under a temporary identity, but there's no parameter for the token. Without it, I get a 403 denied.

I can't even start to make a mkfs.s3ql.

I'm not too sure how to proceed.

Any idea?

**Comment by Kirin-kun** [comment]
After reading the aws doc (https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html) , the headers must contain  x-amz-security-token

Which s3ql doesn't support?

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!

**Comment by brianredbeard** [comment]
Well.... I'm assuming then that this support never made it.  Considering that Google groups requires me to have an account just to view content, this issue was enough for me!
