### ISSUE TITLE
Is there a way to pass suid,dev,exec options to fuse ?

### ISSUE THREAD

**Issue by i0x71** [s3ql/s3ql#162]
By default it mounts the s3 backend with rw,nosuid,nodev,relatime,user_id=0,group_id=0
I would like to use dev and suid instead.
Is there a way i can pass those options ?

Thanks

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!
