### ISSUE TITLE
[question] how to fix corrutped files returned by verify

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#163]
Hi,

is there a way to fix corrupted files returned by s3ql_verify?
I still might have the source files that were backed up to s3ql.

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!
