### ISSUE TITLE
S3QL multi mount RO

### ISSUE THREAD

**Issue by segator** [s3ql/s3ql#177]
Hi i have some experience modifying S3QL code as I implemented Gdrive in the past and works perfect, now i'm thinking how to add multi RO mount support, so 1 RW mount and multiple RO.
maybe @Nikratio  you have some tips for me?

**Comment by mlloewen** [comment]
I would like to see eventually a good file locking method. So that there could be multiple RW mounts. I know this would create more api calls to the back end thus should be in a optional mount flag.

**Comment by powerpaul17** [comment]
I think the problem would be the local database which holds practically all information of the file system. Only the actual data blocks are uploaded/downloaded to/from the backend. (The database is backed up regularly too of course, once every 24h)

**Comment by d--j** [comment]
I suspect this feature will never make it into S3QL. If you need it, your best bet is to mount S3QL somewhere central and re-export it as NFS/Samba share. All clients then do not mount S3QL directly but access it over NFS or CIFS.

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!
