### ISSUE TITLE
Claim mount on other server as a failover

### ISSUE THREAD

**Issue by MrMoronIV** [s3ql/s3ql#19]
I'm trying to setup some kind of failover for when the server where s3ql is mounted dies.
When I mount on a different server it complains that the backend doesn't like it, which makes sense.

What would be the correct way to claim the mount (so to speak) on the second server when this backup server needs to take over?

**Comment by Nikratio** [comment]
You'd have to run fsck.s3ql there and confirm that this is really what you want to do (or use `--force`).

That said, I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support. So if you have further questions, please use the S3QL mailing list. To subscribe, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

In either case, please use the search function before you ask a question - it may have been asked and answered before. Thanks!
