### ISSUE TITLE
[Suggestion/PR] Container-friendly packaging + lifecycle

### ISSUE THREAD

**Issue by Tristan971** [s3ql/s3ql#191]
Hi, thanks for a really cool project (the basis of it is so out there yet so clever, I absolutely love it)

I have been working on coming up with a containerised version of it, but have a couple of questions before going further on my own:

#### 1. Do you prefer "container-friendliness" work to happen as part of this project or separately?

I understand that accepting features rather than having a wrapper project means additional maintenance for you, hence the question.

The current state of things I have is in this project [tristan971/s3ql-docker](https://github.com/Tristan971/s3ql-docker). The usage is from a [k8s statefulset in conjunction with an NFS server](https://github.com/Tristan971/tristan.moe-k8s/blob/master/default/s3ql-nfs/statefulset.yml)

If here, it would probably specifically involve:
- a Dockerfile, 
- publishing images, 
- having a proper container lifecycle handling
  - especially around crashes/kills etc
- coming up with explicit memory/cpu limit handling
  - especially with k8s, we want to avoid the container getting itself killed by the scheduler in an attempt to preserve shared resources :slightly_smiling_face: 

Also, longer term, a Helm chart for easy deployment in a k8s cluster. That would for sure be a separate repository I think as it would
involve other moving parts than the s3ql binaries.

#### 2. In any case, what should a "safe" lifecycle look like?

The [init wrapper](https://github.com/Tristan971/s3ql-docker/blob/master/scripts/s3qlw_init) is what tries to come up with a safe-ish container lifecycle, as follows:
- import authfile to default location
- create mountpoint + cache mountpoint as necessary
- mount the bucket
- use a lock-like file with info to ensure no double-mounting 
  - I realise s3ql seems to guarantee this already, but from the docs it seemed like it merely discouraged it, hinting at it still being possible
- pause in foreground for the container's life with a `tail -f /dev/null`
- trap signals to do cleanup
  - TERM for daemon-requested stop
  - INT for ctrl+c by user
- on cleanup, delete the lockfile then invoke `umount.s3ql`

So there's a few things I'd like to understand for it to be more robust:
  
##### b. if I know for a fact that it was bad cleanup, is it reasonable to just fsck it?
- what about on every container start? (assuming that I do already have a strong guarantee that 2 containers can never be up at the same time)
  
##### c. is there a way to deal with `umount.s3ql` blocking too long before the whole container gets docker-kill'd?
 - even if there was a way to increase the default wait in k8s for example, which is 10s, it might hang around for a long time if the remote API is not responsive or something

Anyway I realise this is a bit more of a question than a bug report, but I hope it's not too bad to read/reply to.

And to be clear, whichever is your answer, I volunteer to handle the implementation of it shall you think it belongs to s3ql rather than a wrapper project.

Thanks for your reading time

**Comment by d--j** [comment]
Hello @Tristan971 

you do know the `--fg` flag of `mount.s3ql`? **exec** `mount.s3ql` as last command in your entry point and you should not need to handle the signals on your own. (Only if CMD is empty/the default). The unmounting should also happen automatically when you send a SIGINT to this process.

I think (I might easily be wrong) that a complicated CMD call like https://github.com/Tristan971/tristan.moe-k8s/blob/7de97b3ce840cebc2a95f00f82ad8e6f5a357773/default/s3ql-nfs/statefulset.yml#L43-L57 is kinda not the Docker way. Environment variables with sound defaults are more common to configure a container.


> a. is it a guarantee that mount.s3ql will fail if another client is connected (or didn't properly cleanup) ?

No. there is no guarantee. If two clients start up nearly simultaneously they both might be able to mount the remote. To get to this state, you need to do stuff seriously wrong (e.g. using a Deployment with rolling restart instead of StatefulSet). I think S3QL's detection simultaneous access is safe enough. You do not need to have a separate lockfile.

> b. if I know for a fact that it was bad cleanup, is it reasonable to just fsck it?

This is the ExecStartPre script I am using for a S3QL systemd service

```bash
#!/bin/bash

# Check for a crashed S3QL
if ls "/mount/point" 2>&1 | grep -Fq 'Transport endpoint is not connected'; then
  fusermount -u "/mount/point"
fi

# Check file system
echo executing fsck.s3ql --batch --authfile /root/.s3ql/authinfo2 --keep-cache --backend-options=tcp-timeout=20,domain=default --cachedir "/cache/dir" "storage-url"
/usr/bin/fsck.s3ql --batch --authfile /root/.s3ql/authinfo2 --keep-cache --backend-options=tcp-timeout=20,domain=default --cachedir "/cache/dir" "storage-url"
FSCK_RESULT=$?
if [[ $FSCK_RESULT != 0 && $FSCK_RESULT != 128 ]]; then
  echo "fsck.s3ql reported errors! exit code $FSCK_RESULT"
  exit $FSCK_RESULT
fi
exit 0

```

If that script exits with something different than `0` then the file system is in a seriously bad state.


> c. is there a way to deal with umount.s3ql blocking too long before the whole container gets docker-kill'd?[...]

10 seconds? That is by far too little time! For bigger file systems you need timeouts of 30 minutes and more. And you _really_ should try to unmount S3QL cleanly. S3QL can almost always repair a forcefully unmounted file system (**if you have the local, up to date database, that is**) but the needed `fsck.s3ql` can take a long time (especially when you use the `--keep-cache` option, since it then needs to check each cache entry if it is dirty)

If you cannot increase the kill timeout, then you need to somehow bring S3QL into a clean state before stoping the container (no dirty cache objects via `s3qlctrl flushcache` and upload the current database via `s3qlctrl upload-meta`) then the unmounting will go thru a fast  path and will probably be done in 10 seconds.


> 1. Do you prefer "container-friendliness" work to happen as part of this project or separately?

I'm just a fellow S3QL user but in my humble opinion S3Ql will probably not include an _official_ Dockerfile. But it might be beneficial to include some parts that make it easier to containerised, tho:

- include a `requirements.txt` (and a `requirements-dev.txt`) that always have a up-to-date set of requirements. (`requirements-dev.txt` would include Cython and Sphinx)
- add an optional readiness/liveliness check via a small embedded HTTP server
- add an optional Prometheus exporter (like this https://github.com/segator/s3ql-prometheus-exporter/blob/master/s3qlprometheus.py)

**Comment by Tristan971** [comment]
Hi @d--j !

Thanks for reading, looking and replying.

> you do know the --fg flag of mount.s3ql
Yes I was aware of it, but didn't think that a SIGINT to `mount.s3ql` guarantees clean unmount (as opposed to a separate `fusermount` based invocation).

> No. there is no guarantee.
Also I was using a `.lockfile` exactly for the purpose you mention of avoiding non-guaranteed cross-mount (hoping that if it is present, an early abort minimizes the risks of corruption of 2 clients running in parallel).

> a complicated CMD [...] is kinda not the Docker way
Fully agreed! This was a day's project that indeed would require quite a bit of tidying in any case!

> This is the ExecStartPre
Oh that is really neat! Mind me stealing it? :grinning: 

> 10 seconds? That is by far too little time! 
That is configurable, it was more a question (that you did answer, thanks) of what kind of timeframe if any I'm guaranteed. Also in the event of an abnormal unscheduling of my container by K8S I'm not sure if there's situation where it might bypass the graceful stop timeouts even if I configured it to last very long...

> For bigger file systems you need timeouts of 30 minutes
Oh wow, what kind of "bigger" do you mean in this case? My use case would be within 2 to 5 TB long term ; is that "big" in this case?

Thankfully I didn't use the `--keep-cache` as I do not need that optimisation in any way

> S3QL will probably not include an official Dockerfile [...]
Yeah agreed, was mostly thinking that it was more polite to ask before assuming that :slightly_smiling_face:

**Comment by d--j** [comment]
> Oh wow, what kind of "bigger" do you mean in this case? My use case would be within 2 to 5 TB long term ; is that "big" in this case?

The bigger the cache, the more dirty blocks need to be uploaded by S3QL on unmount. The bigger the database the longer it takes to upload it on unmount. So if you have 100GB of dirty cache that you have to upload on unmount – this will take some time! The overall size of the filesystem is only relevant for the database/metadata upload. 5TB filesystem size with a reasonable amount of files (< 10 Million) should not be that big of a database (<100MB) and should be no problem.

**Comment by Nikratio** [comment]
Hi @Tristan971,

Thanks for getting in touch! To answer your questions:

I think it would be great to have as much support for running inside a container in the main S3QL repo as possible. This certainly includes things like the Dockerfile, and probably also other necessary adjustments (but this would be more of case by case decision). These days I have little time to work on S3QL, so I certainly wouldn't be able to publish any container images though. It is also not  clear to me how this could be "part" of this project (since the images certainly wouldn't be in the Git repo).

It is not clear to me what you mean with "safe lifecycle". You are listing a number of steps, but I am not sure I understand the problem that you are trying to solve with them. For example, S3QL will prevent simultaneous mounts, but it can only guarantee this for backends with immediate consistency. If this isn't available, then nothing that you do in the container can prevent that (unless you are only concerned about simultaneous mounts by the same host system).

You can reasonably do an fsck on every container start. On a clean unmount, this will be very lightweight.

I am also not sure what you mean with "dealing umount.s3ql blocking too long before the whole container gets docker-kill'd". If you are asking if there is a way to speed-up the unmount then the answer is no - unless you are willing to accept an unclean unmount (in which you can also just kill the mount.s3ql process). Unmount has to upload all dirty data and upload the entire SQLite database, so this may take a while. It seems to me that the best way to handle this is to increases the timeout on the Docker side.

**Comment by Tristan971** [comment]
Thanks for the prompt reply!

> [I] wouldn't be able to publish any container images though
If it is about the process of publishing images, it's quite straightforward through Github Actions, but if you mean you'd rather not become a line of contact to any blind user of the image I can understand that too.

> It is not clear to me what you mean with "safe lifecycle"
Sorry, expressed myself poorly. Rather than a specific problem, I wanted to understand (and make sure my container's configuration to reflect it), what a good balance between performance and data safety was. @d--j's answer gave quite a bit of the information I was seeking regarding that.

> unless you are only concerned about simultaneous mounts by the same host system
Don't think this is worth concerning myself (or others, for that matter) with as it is indeed near-impossible to prevent any situation of multiple clients mounting a bucket

"Reasonable certainty" that it doesn't happen silently suits me well enough :+1: 

> You can reasonably do an fsck on every container start. On a clean unmount, this will be very lightweight.
Thanks, that's very good to know!

> if you are asking if there is a way to speed-up the unmount then the answer is no - unless you are willing to accept an unclean unmount
Fair enough, that was my only fear, because as much as I can make the init script "do the right thing", if it gets booted by whatever schedules the container (k8s here, but could be something like systemd on shutdown) then it's all for nothing in a sense

In any case I'm happy to hear that you are of the preference of having container support in this repository.

What I will do is, following @d--j's recommendations, amend my setup to be more polished, and bring a more polished version of my repo over here within the next couple of days.

**Comment by Nikratio** [comment]
It seems to me that there's no specific AI for this issue, so I'll close this for now. Please do feel free to send pull requests as discussed above.

**Comment by Tristan971** [comment]
Hi, sorry have been a bit busy lately but haven't forgotten!
No need to reopen, I will send a PR hopefully soon-ish!
Cheers

**Comment by Tristan971** [comment]
Hi, I finally had holidays and thus time to look this up, and thus opened #200 for a preview of it that I believe follows most of what we discussed! :slightly_smiling_face:
