### ISSUE TITLE
Suggestion: erasure-coding storage accross multiple providers

### ISSUE THREAD

**Issue by FlorentCoppint** [s3ql/s3ql#218]
Hi,
I recently discovered s3ql and I'm very happy and impressed of its capabilities (coming from UtahFS which lacks of stability).
I was wondering if it could be a good idea (or not) to implement an erasure-coding algorithm to permit storage on multiple S3 provider transparently for the user.
For example, we choose 3 different S3 providers (Scaleway, OVH and Backblaze), we choose k & m erasure-coding parameters (let's say k=2 & m=1) and it could store our file system like a RAID-5 array across the 3 providers, having the "security" of 1 provider failure. It could also correct errors on some objects failures which can always occur.
Erasure-coding permits to adapt the 2 variables k&m to fit the situation. For example, if we have 4 S3 providers, we can do a RAID-5 like storage with k=3 / m=1 or RAID-6 with k=2 / m=2 (having k=m is always like a RAID-1 too)
There is a lot of erasure coding libraries in Python (some of them uses C code for performance).
What do you think about this ?
Thanks.
Flo

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)? 

S3QL is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd
 be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

If you want to discuss the pro's and con's of the idea for now, please use the S3QL mailing list (
I'd like to reserve use of the issue tracker for tracking bugs, not for discussions). To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

**Comment by FlorentCoppint** [comment]
Sorry, mailing-list is a better place for discussion, I close this issue.
