### ISSUE TITLE
`.params` file will get lost if disk is full

### ISSUE THREAD

**Issue by charles-cooper** [s3ql/s3ql#219]
https://github.com/s3ql/s3ql/blob/131d5045801ced69fc326081197745ea9fb3276b/src/s3ql/common.py#L549

Opening .params with `'wb'` truncates the file. If the subsequent write fails (e.g. disk out of space - not theoretical, this actually just happened to me), the params file will be lost. The fix should be to use the idiom of writing to a temporary file and then using `rename` to the target file (which IS atomic on POSIX).

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

S3QL is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by charles-cooper** [comment]
Sure, I can submit a PR. It's not just a disk-out-of-space issue either. It could happen for instance if the OS crashes before the data is flushed.
