### ISSUE TITLE
[Enhance] Upload manifest. 

### ISSUE THREAD

**Issue by nguyenhuuluan434** [s3ql/s3ql#225]
Hi,
Currently, i want to use blocks (without compress, without encrypt without deduplication feature) as segments of large object in Swift Openstack [SLO](https://docs.openstack.org/swift/latest/overview_large_objects.html#module-swift.common.middleware.slo), when i debug the logic of mount to swift backend, i known those blocks of file will be in cache folder and async upload to swift backen. 
Do i can capture last block write to cache finished and trigger upload the blocks of this file to swift? 
My purpose is generate manifest for SLO from segments/blocks anh upload to swift, after that we can download the object by this manifest.

Thanks in advance.

**Comment by d--j** [comment]
So you want to use SLO to be able to download your files directly from Swift (without needing to mount the S3QL filesystem)?

The block cache does not know when a file handle gets closed.
You need to do some serious refactoring to keep track when a file is "finished" (i.e. the file gets closed but what do you do when S3QL crashes? How to recover from that?) in the block cache and beyond.

Anyways, this looks to me quite out of scope of S3QL and I suspect Nikolaus will never consider adding this feature to S3QL (as the issue title suggest you want to happen).

**Comment by nguyenhuuluan434** [comment]
@d--j 
thank you for your comment.

**Comment by Nikratio** [comment]
To be honest, I do not understand what is being asked here. I'm pretty sure I will not work on this, but at this stage I can't tell if I'd accept patches or not since I don't understand the proposal.

**Comment by d--j** [comment]
@Nikratio
> [...] I can't tell if I'd accept patches or not since I don't understand the proposal.

As I understand it, @nguyenhuuluan434 wants S3QL to have a special mode that disables

- encryption (already possible)
- compression (already possible)
- deduplication (needs to be added)

with such a special cased S3QL every file that you create inside a S3QL mount would end up as 10-MB chunked `s3ql_data_xxxx` objects in the object storage.
You only needed to concatenate these blocks and would get the original file. That is what such a SLO manifest does virtually. Since only S3QL knows which `s3ql_data_xxxx` objects belong to a file (and what name/path that file has) S3QL needs to upload these manifests. This enhancement would teach S3QL to do that. It is specific to OpenStack Swift since only this backend has this feature (as I know of).

---

@nguyenhuuluan434 I think you would be better of when you create these SLO manifests when the S3QL filesystem is not mounted. Create a new program that directly opens the database loops over all paths and creates SLO manifests for each of it. When you want to do that "online" while the file system is mounted you (a) need to change big parts of S3QL, (b) will probably never catch all edge cases when a file is ready for manifest upload, or (c) constantly re-create a manifest file for append-only files like log files.

**Comment by nguyenhuuluan434** [comment]
Hi all,
@Nikratio thank you for your comment.

@d--j first of all thank you detail your idea. Yes the feature SLO manifest is only feature of Openstack swift. Base on your recommendation i will try to test create new service, the new service will execute some main task create manifest when new file was created, update manifest when existing file update content, remove manfiest when exist file was deleted. During debug s3ql i had been seeing when FUSE finish write data to block the release funtion, i will trigger the new service query blocks of the file and create manifest for this. Because s3ql using async to write data to block cache and after that block cache will be sync to backend when dirty-block-upload-delay was reached, so in the new service will start new thread to handle logic.

@d--j @Nikratio, thank you in advance for your attention to this matter.
