### ISSUE TITLE
Signed/unsigned issue with a/c/mtime in far future

### ISSUE THREAD

**Issue by r0ps3c** [s3ql/s3ql#294]
Around late 2022, while s3ql was in maintenance mode, I encountered an issue on a machine that had some files with ctimes set in the far future (due to an application bug, I believe), leading to a crash when those were copied over to a (v4.0) s3ql fs. After debugging I worked out that this was due to an overflow, as s3ql/python's int was effectively unsigned whereas sqlite's is signed.

The commit in question is https://github.com/r0ps3c/s3ql/commit/b8d25d58fb7dc0004d34d34d1cc3e9669c2299e1, and I've been running with that code since then with no issues. It did require an fs version bump, hence why I'm bringing this up now with the 5.0 testing/upcoming release. My fork has a number of other changes, mostly around the build system, and together with your 5.0 updates a PR would be a little more complex, but I'm curious what your thoughts are around the above commit and/or getting it integrated?

**Comment by d--j** [comment]
Does your solution handle files with c/m/a times before the [unix epoch](https://en.wikipedia.org/wiki/Unix_time) (1970-01-01)?

When changing the date range of the c/m/a times of S3QL, the new solution should probably be able to handle at least the same date range as other file systems.  
E.g. [Ext4](https://en.wikipedia.org/wiki/Ext4) and [XFS](https://en.wikipedia.org/wiki/XFS) start from `unix epoch - 2147483648 seconds` (1901-12-13).

One easy solution would probably be to use a composite to save the c/m/a times in Sqlite: Seconds since unix epoch and nanoseconds since this second[^1]. Since Sqlite is using [variable length encoding](https://www.sqlite.org/datatype3.html), this should not increase the size of the Sqlite database for "normal" dates (they can be saved with 32 bit for the seconds and 32 bit for the nanoseconds; if you use only nanoseconds they mostly need to be stored as 64 bit integer). You would be able to save c/m/a times that are billions of years in the future or past in the database[^2].

[^1]: like the timespec struct of [<time.h>](https://man7.org/linux/man-pages/man0/time.h.0p.html)

[^2]: I haven't checked but Python's and libfuse's time functions probably have a tighter limit like -9999-12-31 – 9999-12-31.

**Comment by Nikratio** [comment]
Thanks for the report! Yes, I'd be interested in a patch. Would you be able to clean up your commit a bit (it seems like it contains more changes than strictly required) and add a unit test?

**Comment by Nikratio** [comment]
Copying some thoughts from the pull request here:

Timestamps above 2^63 are in the year 2262. Is there a use-case for a file having such a time-stamp? My thinking is that perhaps a better solution would be to return a -EINVAL to userspace. Looking at the original bug report, it seems these timestamps were the result of an application bug. 

If I understand correctly, the fix that's being proposed in #298 is to shift all times by a constant offset before storing them in SQLite. However, this would just increase the range to timestamps up to 2*2^63, i.e., after year 2554+ things would overflow as before. So I'm not sure if this is much better.

Maybe we should instead reduce the timestamp accuracy from nanoseconds to microseconds? That would mean we can represent years beyond 586524.

**Comment by r0ps3c** [comment]
I agree that returning EINVAL seems the simpler and cleaner approach. I don't have a use case driving more significant changes to timestamps, and as this seems to address the fs crash I was seeing, the fix/commit seems like a good solution.
