### ISSUE TITLE
does it mean tthe S3QL development is still alive?

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#304]
I have just seen v4.0.1
and I think I recall pre-release of 5.0.0

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about S3QL rather than a bug report. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.
