### ISSUE TITLE
Provide workaround for OpenStack Swift's server brokenness

### ISSUE THREAD

**Issue by Bourba** [s3ql/s3ql#355]
For the past few days, I've been encountering an error like:

Checking backup 006630ee92 (from 2024-06-28 20:15:43)...
Downloaded 192/3301 metadata blocks (5%)
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==5.1.3', 'console_scripts', 'fsck.s3ql')()
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/fsck.py", line 1344, in main
    verify_metadata_snapshots(backend, count=5, include_most_recent=check_current_metadata)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/fsck.py", line 1442, in verify_metadata_snapshots
    conn = download_metadata(backend, fh.name, params)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/database.py", line 533, in download_metadata
    backend.readinto_fh(obj, fh)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/backends/comprenc.py", line 173, in readinto_fh
    meta_raw = self.backend.readinto_fh(key, buf1)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/backends/swift.py", line 400, in readinto_fh
    return self._readinto_fh(key, fh, fh.tell())
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/backends/swift.py", line 407, in _readinto_fh
    resp = self._do_request('GET', '/%s%s' % (self.prefix, key))
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/backends/swift.py", line 287, in _do_request
    self.conn.discard()
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/http.py", line 1296, in discard
    return eval_coroutine(self.co_discard())
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/http.py", line 1388, in eval_coroutine
    next(it)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/http.py", line 1308, in co_discard
    buf = await self.co_read(BUFFER_SIZE)
  File "/usr/local/lib/python3.7/dist-packages/s3ql-5.1.3-py3.7-linux-x86_64.egg/s3ql/http.py", line 958, in co_read
    raise self._encoding
s3ql.http.UnsupportedResponse: No content-length and no chunked encoding

I've been using S3QL for several years with OpenStack Swift as the backend at OVH. 
I'm using Python 3.7 and S3QL 5.1.3. I also tried with Python 3.8 from another server, but I'm still getting the same result.
The error occurs randomly during mount or fsck operations, not always on the same chunk.
In my desperation, I tried the options `no-feature-detection` and `disable-expect100`.
I think the issue lies with the OpenStack OVH server. What do you think?

**Comment by Nikratio** [comment]
Yes, this is almost certainly an issue with the OpenStack server. It's not sending a Content-Length header (anymore?)

**Comment by d--j** [comment]
Hi @Bourba 

I am too using S3QL with OVH's OpenStack Swift backend. The mentioned options do not help. OVH's load balancers are unfortunately not that spec compliant in error conditions (e.g. they return a 408 Request Time-out error without the client doing anything. Execute `nc www.ovhcloud.com 80` and wait 10 seconds. You will get a HTTP response back. A spec compliant HTTP server would just close the connection. E.g. `nc s3.us-east-2.amazonaws.com 80`)

For my local S3QL packages, I apply the following patches to make S3QL more forgiving:

```patch
--- a/src/s3ql/backends/swift.py
+++ b/src/s3ql/backends/swift.py
@@ -22,6 +22,7 @@
     ConnectionClosed,
     HTTPConnection,
     is_temp_network_error,
+    StateError,
 )
 
 from s3ql.common import copyfh
@@ -554,7 +555,14 @@
         body = '\n'.join(body).encode('utf-8')
         headers = {'content-type': 'text/plain; charset=utf-8', 'accept': 'application/json'}
 
-        resp = self._do_request('POST', '/', subres='bulk-delete', body=body, headers=headers)
+        try:
+            resp = self._do_request('POST', '/', subres='bulk-delete', body=body, headers=headers)
+        except StateError as exc:
+            if 'Previous response not read completely' in str(exc):
+                self.conn.discard()
+                raise HTTPError(408, "OVH Proxy Timeout Error", {})
+            else:
+                raise exc
 
         # bulk deletes should always return 200
         if resp.status != 200:

```

```patch
Subject: [PATCH] Hotfix for broken OVH load-balancer
---
--- a/src/s3ql/backends/swift.py
+++ b/src/s3ql/backends/swift.py
@@ -23,6 +23,7 @@
     HTTPConnection,
     is_temp_network_error,
     StateError,
+    UnsupportedResponse,
 )
 
 from s3ql.common import copyfh
@@ -158,6 +159,12 @@
         ):
             return True
 
+        elif isinstance(exc, UnsupportedResponse) and ('No content-length and no chunked encoding' in str(exc)):
+            body = self.conn.read_raw(2048)
+            self.conn.discard()
+            log.error('bad server response (protocol error). Got: %s', body.decode('utf-8', errors='backslashreplace'))
+            return True
+
         return False
 
     def _get_conn(self):

```


I have not proposed to upstream the patches since – when I remember correctly – @Nikratio does not like for S3QL to support any non-spec-compliant storage servers.

**Comment by Bourba** [comment]
I just tested it, it works. I did see the error pop up occasionally, but s3ql kept going with its process. I didn't think I'd get a response, let alone so quickly. Thank you very much.

**Comment by Nikratio** [comment]
I'm not fundamentally opposed to adding workarounds for specific backends. I think they should satisfy a few conditions though:

- Not have the risk of hiding other problems
- Not be enabled unless needed
- Not significantly decrease the maintainability of the overall code base

For the above patch, I'd be worried that it is applied to any Swift server (but this could be addressed by making an OpenStack specific backend or enabling the workaround only if a specific option is passed), and that it could it hide real problems (`StateError` normally indicates a problem in S3QL code, and helped discover a bug just this week). 

Not sure if there's a way to make this more targeted instead of catching any StateError?

**Comment by Bourba** [comment]
I understand Nick's argument, but unfortunately, my comprehension level might be limited. In the case of OVH, the server returns a 500 error. Is the 500 error a common response for s3ql? I think that when the server encounters this error due to a temporary problem, by renewing the request several times at a few seconds interval, we obtain successful access to the same request. Is my point useful? In any case, thank you for this 'patch' which clearly saved me, as I no longer had access to my file systems. And thanks to everyone.
