### ISSUE TITLE
How does s3ql interact with S3 Glacier?

### ISSUE THREAD

**Issue by Torbe** [s3ql/s3ql#59]
I went up and down the Internet to find a definitive answer to this question and found [this](https://webcache.googleusercontent.com/search?q=cache:wGX3dlIwNmEJ:https://bitbucket.org/nikratio/s3ql/issues/170/transition-infrequently-used-data-files-to+&cd=1) and [that](https://groups.google.com/forum/#!topic/s3ql/24GBR0OgTnY). But I still like to get more information on the implications of using Glacier.

My plan is to use a S3 Lifecycle rule to transfer infrequently used files to Glacier to significantly save costs. I understand that s3ql access to glaciered files is somewhat problematic. But does anybody know more about exactly how problematic this can be? Will the consistency of data be endangered or will s3ql simply trigger warnings without crashing?

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!

**Comment by Torbe** [comment]
I want to argue that this is an issue with s3ql itself, although not a bug. Maybe it could be labeled feature request or boundaries of use.
I have no problem with installing or using s3ql, it's more about the technical implications of using S3 Glacier. I would appreciate this issue to be reopened and me not being forced to subscribe to a mailing-list.
