### ISSUE TITLE
Any SSH server as a remote backend?

### ISSUE THREAD

**Issue by imperative** [s3ql/s3ql#67]
It would be very useful to add an ability to use an SSH connection to any server as a remote backend, similar to the way `sshfs(1)` does this. Unfortunately, `sshfs(1)` has very inferior caching functionality which breaks apart (in terms of user experience) in case there is any significant network latency. The caching and asynchronous nature of this application would make a much better sshfsing experience than `sshfs(1)` itself.

**Comment by szepeviktor** [comment]
SSH is not a HTTP-based protocol :(

**Comment by imperative** [comment]
I understand that this is a (possibly quite big) feature request and it might not be a priority, but I think there should be an issue about this to indicate that there is in fact some demand and a good usage case. Sshfs performance is really lacking. The only solution is to make its cache times very long, and then it does not properly update quick changes... All operations are synchronous it seems, network IO in threads that should be responsive... Too little granularity in cache settings... etc.. I think sshfs was meant to be used on LAN. (Is there even a possibility to restore connection in case of a short network failure?)

**Comment by Nikratio** [comment]
As I wrote above, I don't see a reason why a native SSH backend would work better than local backend + SSHFS. This is why the native backend does not exist anymore.

Browsing with the local backend will requires no network connection, just like with the S3 backend. So SSHFS latency should not be a problem.

That said, I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support. So if you have further questions, please use the S3QL mailing list. To subscribe, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

**Comment by imperative** [comment]
Sorry, the question was not meant as a support, but rather to figure out if this feature already exists (using the options you mentioned instead of a native backend) or not. Your answer clearly explains that it does in fact exist, so the issue is resolved and rightfully closed. Thank your for your work!
