### ISSUE TITLE
AWS S3 Backend: add more storage class options

### ISSUE THREAD

**Issue by pheanex** [s3ql/s3ql#77]
What do you think about adding the storage class "ONEZONE_IA" for the aws s3 backend?
(And maybe also "INTELLIGENT_TIERING"?)
See **x-amz-storage-class** in [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)

**Comment by Nikratio** [comment]
Thanks for the suggestion! I don't have a personal interest, but I am not opposed to merging the functionality if someone sends a pull request.

S3QL is a fully volunteer driven project[1]. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

[1] Actually, that's not strictly true. I do offer paid consulting with discounts for code that makes it into the official S3QL release. Contact me privately if that's something you'd be interested in.

**Comment by pheanex** [comment]
Nice, I'll create a PR then :smile: 
Thank you @Nikratio
