### ISSUE TITLE
Question: 64 bit inodes

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#97]
I noticed fsck is triggered if you have inodes larger than 2**31 ... I was under the impression fuse uses 64 bit inodes, so wonder what the reason for that is?

**Comment by Nikratio** [comment]
libfuse supports only 32 bit inodes when running on 32 bit systems (a historical oversight). Therefore, S3QL also uses only 32 bit (so that filesystems can be mounted on 32 and 64 bit systems). This has been fixed in libfuse 3, so it will become available to S3QL as well in the future (probably around September).
